### ISSUE TITLE
build_universal_framework.sh fails with yarn workspaces

### ISSUE THREAD

**Issue by birkir** [wix/Detox#1610]
I have a mono repo (lerna) with two react native apps and some shared packages.

- /packages/app1
- /packages/app2
- /packages/shared

When I do `lerna bootstrap`, the script `build_universal_framework.sh` fails in the postinstall.

I found the root cause to be https://github.com/wix/Detox/blob/master/detox/scripts/build_universal_framework.sh#L63

> mv: cannot move X to Y: Directory not empty

This is because yarn workspaces will run postinstall at the same time on the two separate packages (app1 and app2) so the check will pass that the framework has not been built and goes ahead and builds it (twice) and the one that takes longer will fail.

Possible fix is to force move (with the `-f` flag), or create some sort of a lockfile to ensure the framework will only be built once.

On my CircleCI environment, I have a step that does `npm install -g detox` so that the framework will be prebuilt before going into `lerna bootstrap`.

**Comment by LeoNatan** [comment]
Not good. The build script should not run twice.

**Comment by kristfal** [comment]
Also experiencing this when upgrading to 14.0.3. 

It used to work on older versions of Detox, so I'm bisecting trying to find the breaking change.

**Comment by LeoNatan** [comment]
I doubt that. The script hasn't changed in a while, and has never supposed running concurrently.

**Comment by LeoNatan** [comment]
Seeing as how macOS doesn't have flock or lockfile for atomic-level file locking, I don't see a way to solve this elegantly. We could write our own binary, but with changes to macOS Catalina that might require notarization even for command-line binaries, we won't be venturing into that adventure anytime soon.

A workaround that I can suggest here is "pre-heating" the Detox cache by installing the Detox version you are using before you run the problematic yarn scenario.

**Comment by PierreCapo** [comment]
@birkir can you confirm that a temporary workaround for your CI was to do a 
```bash
npm install -g detox
```
before doing the `npm install`

**Comment by birkir** [comment]
@PierreCapo  I can confirm.

Here is the part from my circleci.yml
```yml
      - run:
          name: Install Detox
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew
            HOMEBREW_NO_AUTO_UPDATE=1 brew install --HEAD applesimutils
            npm install -g detox-cli
            npm install -g detox
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
```
