### ISSUE TITLE
tests failing in Travis and Semaphore

### ISSUE THREAD

**Issue by andykitt** [wix/Detox#1678]
I've been trying to get detox tests passing in a CI for a few days and it keeps failing on the tests. The same error in Travis and Semaphore. The error in my semaphore pipeline is :

```Error: /Users/semaphore/Library/Detox/ios/244486fcee9ff2e760b250ebcbb6568e63bc34d2/Detox.framework could not be found, this means either you changed a version of Xcode or Detox postinstall script was unsuccessful.
--
  | To attempt a fix try running 'detox clean-framework-cache && detox build-framework-cache'
  | at SimulatorDriver.prepare (/Users/semaphore/streamline/node_modules/detox/src/devices/drivers/SimulatorDriver.js:32:13)
  | at processTicksAndRejections (internal/process/next_tick.js:81:5)
  | detox[12791] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onAfterAll()
  | detox[12791] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=acd21bfe-fc58-c770-69e2-116b5ae1be27
  | detox[12791] DEBUG: [DetoxServer.js/WS_CLOSE] Detox server connections terminated gracefully
```

semaphore.yml -
```
version: v1.0
name: Semaphore React Native Pipeline
execution_time_limit:
  minutes: 10
agent:
  machine:
    type: a1-standard-4
    os_image: macos-mojave-xcode10
blocks:
  - name: Install dependencies
    task:
      jobs:
        - name: npm install and cache
          commands:
            - xcrun simctl list
            # Get the latest version of our source code from GitHub:
            - checkout
            # Restore dependencies from cache. This command will not fail in
            # case of a cache miss. In case of a cache hit, npm install will
            # run very fast.
            # For more info on caching, see https://docs.semaphoreci.com/article/68-caching-dependencies
            - cache restore node-modules-$SEMAPHORE_GIT_BRANCH-$(checksum package-lock.json),node-modules-$SEMAPHORE_GIT_BRANCH,node-modules-master
            - npm install
            # Store the latest version of node modules in cache to reuse in
            # further blocks:
            - cache store node-modules-$SEMAPHORE_GIT_BRANCH-$(checksum package-lock.json) node_modules
  - name: Run tests
    task:
      prologue:
        commands:
          # Download source code from GitHub:
          - checkout
          - cache restore node-modules-$SEMAPHORE_GIT_BRANCH-$(checksum package-lock.json),node-modules-$SEMAPHORE_GIT_BRANCH,node-modules-master
      jobs:
        - name: e2e tests
          commands:
            # Install dependencies for detox.js
            - brew tap wix/brew
            - brew install applesimutils
            - cache restore node-modules-$SEMAPHORE_GIT_BRANCH-$(checksum package-lock.json),node-modules-$SEMAPHORE_GIT_BRANCH,node-modules-master
            - npm install -g detox@12.7.0
            - cache store node-modules-$SEMAPHORE_GIT_BRANCH-$(checksum package-lock.json) node_modules
            - cd ios && pod install && cd ..
            # build and test
            - detox build --configuration ios.sim.debug
            - detox clean-framework-cache && detox build-framework-cache
            - detox test --configuration ios.sim.debug --cleanup --loglevel trace
```

I haven't been able to find any answer via stackoverflow and other sources.
