### ISSUE TITLE
Bitrise Hello World Example hangs on detox.init

### ISSUE THREAD

**Issue by jamesopti** [wix/Detox#1753]
I'm trying to get a different repo setup with detox and to debug the basics, I went through the react-native-cli getting started and am trying to run the simplest detox test with it.

I'm using a free Bitrise account, and the project is public. You can see a failed build here: https://app.bitrise.io/build/e7926ddfc759288f#?tab=log

The repo is also public: https://github.com/jamesopti/react-native-test/blob/add_detox/AwesomeProject/e2e/firstTest.spec.js

The specific error I'm encountering is the `device` and `element` globals not being defined (see log below or in the link above).

Is there some basic config with Bitrise that I'm missing? The test runs locally for me just fine.

Thanks in advance!

**Bitrise Error Log**
```
Example: should have welcome screen
Example: should have welcome screen [FAIL]
FAIL e2e/firstTest.spec.js (122.008s)
  Example
    ✕ should have welcome screen (8ms)
  ● Example › should have welcome screen
    Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
      at mapper (../node_modules/jest-jasmine2/build/queueRunner.js:25:45)
  ● Example › should have welcome screen
    ReferenceError: device is not defined
      1 | describe('Example', () => {
      2 |   beforeEach(async () => {
    > 3 |     await device.reloadReactNative();
        |           ^
      4 |   });
      5 | 
      6 |   it('should have welcome screen', async () => {
```

**bitrise.yml**
```
---
format_version: '8'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: react-native
trigger_map:
- push_branch: "*"
  workflow: primary
- pull_request_source_branch: "*"
  workflow: primary
workflows:
  deploy:
    description: "## ..."
    steps:
    - activate-ssh-key@4.0.3:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.17: {}
    - script@1.1.5:
        title: Do anything with Script step
    - yarn@0.1.0:
        inputs:
        - workdir: AwesomeProject
        - command: install
    - install-missing-android-tools@2.3.7:
        inputs:
        - gradlew_path: "$PROJECT_LOCATION/gradlew"
    - android-build@0.10.0:
        inputs:
        - project_location: "$PROJECT_LOCATION"
    - certificate-and-profile-installer@1.10.1: {}
    - xcode-archive@2.7.0:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
        - export_method: "$BITRISE_EXPORT_METHOD"
        - configuration: Release
    - deploy-to-bitrise-io@1.9.2: {}
  primary:
    steps:
    - activate-ssh-key@4.0.3:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.17: {}
    - yarn@0.1.0:
        inputs:
        - workdir: AwesomeProject
        - command: install
        title: Yarn Install
    - yarn@0.1.0:
        inputs:
        - workdir: AwesomeProject
        - command: test
        title: Unit tests
    after_run:
    - detox
  detox:
    steps:
    - cocoapods-install@1.9.1:
        inputs:
        - source_root_path: "$BITRISE_SOURCE_DIR/AwesomeProject/ios"
    - npm@1.1.0:
        title: Install Global
        inputs:
        - workdir: "$BITRISE_SOURCE_DIR/AwesomeProject"
        - command: install -g detox-cli react-native-cli
    - script@1.1.5:
        inputs:
        - working_dir: "$BITRISE_SOURCE_DIR/AwesomeProject"
        - content: |-
            #!/usr/bin/env bash

            brew tap facebook/fb
            export CODE_SIGNING_REQUIRED=NO
            brew install fbsimctl
            brew tap wix/brew
            brew install applesimutils --HEAD
        title: Install detox utils
    - script@1.1.5:
        inputs:
        - working_dir: "$BITRISE_SOURCE_DIR/AwesomeProject"
        - content: |-
            #!/usr/bin/env bash

            detox build --configuration ios.sim.debug
        title: Detox Build
    - script@1.1.5:
        inputs:
        - working_dir: "$BITRISE_SOURCE_DIR/AwesomeProject"
        - content: |-
            #!/usr/bin/env bash

            detox test --configuration ios.sim.debug --cleanup
        title: Detox Test
app:
  envs:
  - opts:
      is_expand: false
    PROJECT_LOCATION: AwesomeProject/android
  - opts:
      is_expand: false
    MODULE: app
  - opts:
      is_expand: false
    VARIANT: ''
  - opts:
      is_expand: false
    BITRISE_PROJECT_PATH: AwesomeProject/ios/AwesomeProject.xcworkspace
  - opts:
      is_expand: false
    BITRISE_SCHEME: AwesomeProject
  - opts:
      is_expand: false
    BITRISE_EXPORT_METHOD: ad-hoc
meta:
  bitrise.io:
    machine_type: elite

```
