### ISSUE TITLE
Running Tests in Github Actions CI environment

### ISSUE THREAD

**Issue by jakeleboeuf** [wix/Detox#1766]
### I have Detox up and running locally, but am struggling to iron out the kinks in CI (Github Actions).

Everything looks like it is ready and available (`detox build` seems to exit successfully), but the tests timeout before connecting to the `WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:`

The full `detox test --trace` output is [here](https://gist.github.com/jakeleboeuf/45a70e7c27a0994e02999521613d62f6).

My workflow looks like this:

```yml
name: "Wena CI"
on: [push]

jobs:
  build:
    name: "Build And Test"
    runs-on: "macOS-latest"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.6

      - name: Install Homebrew
        run: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

      - name: Install Detox Tools
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Install Yarn
        run: YARN_GPG=NO curl -o- -L https://yarnpkg.com/install.sh | bash

      - name: Switch XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Install NPM Dependencies
        run: yarn --frozen-lockfile

      - name: Install CocoaPods CLI
        run: sudo gem install cocoapods -v 1.8.4

      - name: Install Pods
        run: |
          cd ios
          pod repo update
          pod install
          cd ../

      - name: Detox Build
        run: detox build

      - name: Detox Test
        run: detox test --trace
```
