### ISSUE TITLE
Sample Travis CI config for Detox tests

### ISSUE THREAD

**Issue by hendricius** [wix/detox#202]
Hi folks,

thanks for the great software. We are using Detox and like it a lot. We used Appium before and sometimes received random errors. The tests are now running way faster.

In our company we are using Travis CI internally. I wonder if someone has a working Travis Setup he could share? For some reason the tests are failing on Travis for us.

This is our `.travis.yml` file. I copied the settings from this repo.

```
# Hepburn
language: objective-c
osx_image: xcode8.3
env:
  global:
    - NODE_VERSION=stable

install:
  - brew install yarn
  - brew tap facebook/fb
  - export CODE_SIGNING_REQUIRED=NO
  - brew install fbsimctl --HEAD
  - brew tap wix/brew
  - brew install applesimutils --HEAD
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g lerna@2.0.0-rc.4 >/dev/null 2>&1
  - npm install -g react-native-cli >/dev/null 2>&1
  - npm install -g detox-cli >/dev/null 2>&1
  - gem install xcpretty >/dev/null 2>&1
  - yarn install

before_script:
  - travis_wait yarn run build:release:ios

script:
  - yarn run lint
  - yarn run detox:test:ios:release

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/Library/Caches/Homebrew

```

Here is our `circle.yml` file with which the tests are working:

```
machine:
  xcode:
    version: 9.0
dependencies:
  override:
    - brew install node@8
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install yarn
    - brew tap facebook/fb
    - export CODE_SIGNING_REQUIRED=NO && brew install fbsimctl --HEAD
    - fbsimctl list
    - brew tap wix/brew
    - brew install --HEAD applesimutils
    - node -v
    - yarn install
  cache_directories:
    - ~/.cache/yarn

compile:
  override:
    - yarn run build:release:ios

test:
  override:
    - yarn run lint
    - yarn run detox:test:ios:release

```

I copied the settings from this repo.

This is the error we are then getting when we run the detox tests:

```
detox info 7: com.ewyso.EwysoSmartHome launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F ~/Library/Developer/CoreSimulator/Devices/80BE80F4-C243-43F0-BD95-5CB085DAD04F/data/tmp/detox.last_launch_app_log.{out,err} 
  1) "before all" hook
  0 passing (2m)
  1 failing
  1)  "before all" hook:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  
child_process.js:631
    throw err;
    ^
Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.sim.release    
    at checkExecSyncError (child_process.js:588:13)
    at Object.execSync (child_process.js:628:13)
    at Object.<anonymous> (/Users/travis/build/ewyso/mobileapp/node_modules/detox/local-cli/detox-test.js:43:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn run detox:test:ios:release" exited with 1.


```

**Comment by rotemmiz** [comment]
It's hard to tell what your problem is, post your yarn scripts and your stdout/stderr logs here, maybe they will help shed some light on the hanged test.
In addition, run detox test in verbose mode using  `--loglevel verbose` and post output as well.

**Comment by hendricius** [comment]
Thanks for the tips. This is the verbose log. I have no `Simulator.app` inside of `/Applications` on the machine.

```
detox info 19:35:12: server listening on localhost:57662...
detox verb ws onOpen [object Object]
detox verb ws send: {"type":"login","params":{"sessionId":"b610e35a-bada-7522-e670-1bb97426db0c","role":"tester"},"messageId":0}
detox verb ws onMessage: {"type":"loginSuccess","params":{"sessionId":"b610e35a-bada-7522-e670-1bb97426db0c","role":"tester"},"messageId":0}
detox verb ws
detox verb 1: fbsimctl --json "iPhone 7" --first 1 --simulators list
detox info 1: Listing devices...
detox verb 2: fbsimctl --json 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 list
detox verb 3: /bin/bash -c '`xcode-select -p`/Applications/Simulator.app/Contents/MacOS/Simulator --args -CurrentDeviceUDID 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 -ConnectHardwareKeyboard 0 -DeviceSetPath ~/Library/Developer/CoreSimulator/Devices > /dev/null 2>&1 < /dev/null &'
detox info 3: Launching device 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1...
detox verb 4: fbsimctl --json --state booted 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 list
detox info 4: Waiting for device 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 to boot...
detox info 4: Device 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 booted
detox verb 5: fbsimctl --json 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 uninstall com.ewyso.EwysoSmartHome
detox info 5: Uninstalling com.ewyso.EwysoSmartHome...
detox verb 6: fbsimctl --json 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 install /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app
detox info 6: Installing /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app...
detox info 6: Installing /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app...
detox info 6: Installing /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app...
detox info 6: Installing /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app...
detox info 6: Installing /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app...
wdetox info 6: Installing /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app...
detox info 6: Installing /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app...
detox info 6: Installing /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app...
detox info 6: Installing /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app...
detox info 6: Installing /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app...
  1) "before all" hook

  0 passing (52s)
  1 failing

  1)  "before all" hook:
     Error: Command failed: fbsimctl --json 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 install /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app
 `fbsimctl --json 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 install /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app` (exited with error code 1)
      at callback (node_modules/child-process-promise/lib/index.js:33:27)
      at ChildProcess.exithandler (child_process.js:277:5)
      at maybeClose (internal/child_process.js:897:16)
      at Socket.stream.socket.on (internal/child_process.js:340:11)
      at Pipe._handle.close [as _onclose] (net.js:549:12)



child_process.js:631
    throw err;
    ^
```

**Comment by hendricius** [comment]
Also interestingly it seems the simulator was not installed in Xcode:

![image](https://user-images.githubusercontent.com/816859/28336476-6c42e032-6c02-11e7-85a4-c248e21bfa34.png)

**Comment by rotemmiz** [comment]
Try running `fbsimctl --json 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 install /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app
 `fbsimctl --json 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 install /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app` and see what the output is.
You may have a broken version of fbsimctl

**Comment by hendricius** [comment]
Sure. Thanks.

```
Traviss-Mac-487:Applications travis$ fbsimctl --json 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 install /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app
{"event_type":"started","timestamp":1500407512,"subject":"\/Users\/travis\/build\/ewyso\/mobileapp\/ios\/build\/Build\/Products\/Debug-iphonesimulator\/EwysoSmartHome.app","target":{"arch":"x86_64","state":"Shutdown","model":"iPhone 7","name":"iPhone 7","os":"iOS 10.0","udid":"15E2107D-EAD2-4E1F-8BC3-59E58E750FB1"},"event_name":"install"}
{"event_type":"discrete","timestamp":1500407512,"subject":"Error Domain=com.facebook.FBSimulatorControl Code=0 \"Failed to install Application Name: EwysoSmartHome | ID: com.ewyso.EwysoSmartHome with options {\n    CFBundleIdentifier = \"com.ewyso.EwysoSmartHome\";\n}\" UserInfo={NSLocalizedDescription=Failed to install Application Name: EwysoSmartHome | ID: com.ewyso.EwysoSmartHome with options {\n    CFBundleIdentifier = \"com.ewyso.EwysoSmartHome\";\n}, NSUnderlyingError=0x7fcbb3f46d90 {Error Domain=com.apple.CoreSimulator.SimError Code=164 \"Unable to lookup in current state: Shutdown\" UserInfo={NSLocalizedDescription=Unable to lookup in current state: Shutdown}}}","event_name":"failure"}
```

**Comment by rotemmiz** [comment]
Is the simulator up ?

**Comment by hendricius** [comment]
Nope, it doesn't seem to boot.

`/bin/bash -c '`xcode-select -p`/Applications/Simulator.app/Contents/MacOS/Simulator --args -CurrentDeviceUDID 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 -ConnectHardwareKeyboard 0 -DeviceSetPath ~/Library/Developer/CoreSimulator/Devices > /dev/null 2>&1 < /dev/null &'` this should boot it right?

**Comment by hendricius** [comment]
I will try some more instructions from here and report back: https://github.com/wix/AppleSimulatorUtils

Thanks for the help!

**Comment by hendricius** [comment]
Ok I managed to get the simulator up and running. Not sure why, but the wrong simulator was booted up. Despite my package.json saying this:

```
  "detox": {
    "configurations": {
      "ios.sim.release": {
        "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/EwysoSmartHome.app",
        "build": "echo 42",
        "type": "ios.simulator",
        "name": "iPhone 7"
      },
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app",
        "build": "echo 42",
        "type": "ios.simulator",
        "name": "iPhone 7"
      }
    }
  }
```
Looks good right? Only concern, locally my tests are run using iOS 10.3. But in the simulator iOS 10.0 is installed. Can we specify an iOS version as well? I tried combinations like: `iPhone 6 iOS 10.3`


Now he is running the tests:

```
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.sim.debug --loglevel verbose


detox info 09:27:13: server listening on localhost:49765...
detox verb ws onOpen [object Object]
detox verb ws send: {"type":"login","params":{"sessionId":"2ea80f84-3351-ef1f-f046-39b513acc080","role":"tester"},"messageId":0}
detox verb ws onMessage: {"type":"loginSuccess","params":{"sessionId":"2ea80f84-3351-ef1f-f046-39b513acc080","role":"tester"},"messageId":0}
detox verb ws
detox verb 1: fbsimctl --json "iPhone 7" --first 1 --simulators list
detox info 1: Listing devices...
detox verb 2: fbsimctl --json 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 list
detox info Device 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 is already booted
detox verb 3: fbsimctl --json 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 uninstall com.ewyso.EwysoSmartHome
detox info 3: Uninstalling com.ewyso.EwysoSmartHome...
detox info 3: com.ewyso.EwysoSmartHome uninstalled
detox verb 4: fbsimctl --json 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 install /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app
detox info 4: Installing /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app...
detox info 4: /Users/travis/build/ewyso/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/EwysoSmartHome.app installed
detox verb 5: /bin/cat /dev/null >~/Library/Developer/CoreSimulator/Devices/15E2107D-EAD2-4E1F-8BC3-59E58E750FB1/data/tmp/detox.last_launch_app_log.out 2>~/Library/Developer/CoreSimulator/Devices/15E2107D-EAD2-4E1F-8BC3-59E58E750FB1/data/tmp/detox.last_launch_app_log.err && SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/travis/build/ewyso/mobileapp/node_modules/detox/Detox.framework/Detox" /usr/bin/xcrun simctl launch --stdout=/tmp/detox.last_launch_app_log.out --stderr=/tmp/detox.last_launch_app_log.err 15E2107D-EAD2-4E1F-8BC3-59E58E750FB1 com.ewyso.EwysoSmartHome --args -detoxServer ws://localhost:49765 -detoxSessionId 2ea80f84-3351-ef1f-f046-39b513acc080
detox info 5: Launching com.ewyso.EwysoSmartHome...
detox info 5: com.ewyso.EwysoSmartHome launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F ~/Library/Developer/CoreSimulator/Devices/15E2107D-EAD2-4E1F-8BC3-59E58E750FB1/data/tmp/detox.last_launch_app_log.{out,err}
detox verb ws send: {"type":"isReady","params":{},"messageId":-1000}
  1) "before all" hook

  0 passing (2m)
  1 failing

  1)  "before all" hook:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.




child_process.js:631
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.sim.debug --loglevel verbose
    at checkExecSyncError (child_process.js:588:13)
    at Object.execSync (child_process.js:628:13)
    at Object.<anonymous> (/Users/travis/.nvm/versions/node/v8.1.4/lib/node_modules/detox/local-cli/detox-test.js:46:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
```

Then I checked the last launch logs. It seems the device idles at some point?

```
objc[11398]: Class PLBuildVersion is implemented in both /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x1191c9910) and /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x118ff3210). One of the two will be used. Which one is undefined.
2017-07-19 09:27:39.922 EwysoSmartHome[11398:35089] Crash handler setup started.
2017-07-19 09:27:39.932 EwysoSmartHome[11398:35089] Crash handler setup completed.
2017-07-19 09:27:39.932 EwysoSmartHome[11398:35089] Enabling accessibility for automation on Simulator.
2017-07-19 09:27:40.683 EwysoSmartHome[11398:35089] kGREYConfigKeyScreenshotDirLocation is to be deprecated in the 1.10.0 release. Please use the kGREYConfigKeyArtifactsDirLocation config key instead.
2017-07-19 09:27:44.968 [info][tid:main][RCTBatchedBridge.m:77] Initializing <RCTBatchedBridge: 0x6000001ad2e0> (parent: <RCTBridge: 0x6000000d2d70>, executor: RCTJSCExecutor)
2017-07-19 09:27:45.093 [warn][tid:main][RCTBatchedBridge.m:115] Failed to load source: Error Domain=RCTErrorDomain Code=0 "No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle." UserInfo={NSLocalizedDescription=No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.}
2017-07-19 09:27:45.111 EwysoSmartHome[11398:35089] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.JSCExecutorQueue[0x6000000f5200]>
2017-07-19 09:27:45.422 EwysoSmartHome[11398:35089] ☣️ DETOX:: Detox Action Sent: login
2017-07-19 09:27:46.394 [fatal][tid:main] No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.
2017-07-19 09:27:46.536 [warn][tid:com.facebook.react.JavaScript][RCTModuleData.mm:220] RCTBridge required dispatch_sync to load RCTDevSettings. This may lead to deadlocks
🔵-[Settings init] Settings loaded
🔵-[Settings setOdometer:] 0
2017-07-19 09:27:47.172 EwysoSmartHome[11398:35089] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.RNBackgroundGeolocationQueue[0x6080000f6a80]>
2017-07-19 09:27:47.179 EwysoSmartHome[11398:35089] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.OrientationQueue[0x6000000fd800]>
2017-07-19 09:27:47.180 EwysoSmartHome[11398:35089] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.RNBackgroundFetchQueue[0x6000000fd980]>
2017-07-19 09:27:50.546 EwysoSmartHome[11398:35089] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.VydiaRNFileUploaderQueue[0x6080000f7100]>
2017-07-19 09:27:50.546 EwysoSmartHome[11398:35089] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.SourceCodeQueue[0x6000000fed00]>
2017-07-19 09:27:50.657 EwysoSmartHome[11398:35089] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.AccessibilityManagerQueue[0x6080000f7280]>
2017-07-19 09:27:50.671 EwysoSmartHome[11398:35089] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.DevLoadingViewQueue[0x6080000f7200]>
2017-07-19 09:27:50.671 EwysoSmartHome[11398:35089] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.PlatformConstantsQueue[0x6080000f7500]>
2017-07-19 09:27:50.672 EwysoSmartHome[11398:35089] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.I18nManagerQueue[0x6080000f7380]>
2017-07-19 09:27:50.717 EwysoSmartHome[11398:35089] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.SettingsManagerQueue[0x6000000edd80]>
2017-07-19 09:27:50.740 [warn][tid:main][RCTEventEmitter.m:54] Sending `providerchange` with no listeners registered.
2017-07-19 09:27:50.741 EwysoSmartHome[11398:35089] ☣️ DETOX:: Detox Action Received: loginSuccess
2017-07-19 09:27:51.456 EwysoSmartHome[11398:35089] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.RedBoxQueue[0x6080000f5780]>
2017-07-19 09:29:13.123 EwysoSmartHome[11398:35089] ☣️ DETOX:: Closed: Stream end encountered
```

And I also grabbed the full device logs here: http://termbin.com/mzfq. Those are the ones I got from the `fbsimctl` command

What else could I debug to find the issue? The funny thing, it works on Circle, locally, but not on Travis.

**Comment by rotemmiz** [comment]
1. Seems like your app wasn't built correctly, the log says `Make sure you're running a packager server or have included a .jsbundle file in your application bundle." UserInfo={NSLocalizedDescription=No bundle URL present.`

2. You can use `iPhone 6, iOS 10.3`. I took a look in the docs, and noticed the formatting broke the entire text in the table, so here it is, updated. [https://github.com/wix/detox/blob/master/docs/APIRef.Configuration.md#device-configuration](Device Configuration)

**Comment by hendricius** [comment]
1. Thanks. So I double checked not sure why, but another simulator was launched. That caused the issues. So I just called another `fbsimctl shutdown`.

2. Yes, thanks that works.

So here is my final `.travis.yml` config. I guess I spend around 10-15 hours in total of trying to get this to run. But now the tests pass. Interestingly CircleCI is around 50% faster in total.


```
# Hepburn
language: objective-c
osx_image: xcode9
xcode_sdk: iphonesimulator11.0
env:
  global:
    - NODE_VERSION=stable

install:
  - brew update
  - sudo launchctl limit maxfiles 2048 unlimited
  - sudo ulimit -n 10000
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - brew install watchman
  - brew install yarn
  - brew tap facebook/fb
  # START HACK This is a hack since the homebrew version updates daily. we install a
  # specific working version. In the future install a version of fbsimctl
  # that works.
  - git clone https://github.com/facebook/FBSimulatorControl.git
  - cd FBSimulatorControl && git checkout 2a461c4e31f12b29974a5a6d184126c2526c62d1 && ./build.sh fbsimctl build output && cd ../
  - mv FBSimulatorControl/output/Frameworks/* /usr/local/Frameworks/
  - mv FBSimulatorControl/output/bin/* /usr/local/bin/
  # END HACK
  #  Add those lines again once the hack is removed. Remove the --HEAD flag.
  #- brew tap facebook/fb
  #- export CODE_SIGNING_REQUIRED=NO && brew install fbsimctl --HEAD
  - export CODE_SIGNING_REQUIRED=NO
  - brew tap wix/brew
  - brew install applesimutils --HEAD
  - yarn install

before_script:
  - travis_wait yarn run build:release:ios
  - fbsimctl shutdown

script:
  - yarn run lint
  - yarn run detox:test:ios:release --loglevel verbose

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/Library/Caches/Homebrew
```
