### ISSUE TITLE
React-Native + Detox + Gitlab-ci + AWS EC2 / Cannot boot Android Emulator with the name

### ISSUE THREAD

**Issue by chassierPA** [wix/Detox#2472]
**Describe the bug**
My goal is to run unit test e2e detox for a mobile application in react-native from a Gitlab-ci on a AWS ec2 instance

- AWS EC2: c5.xlarge 4 CPU / 8GB RAM

I just create an instance ec2 c5.xlarge on AWS and setup docker and gitlab-runner with docker executor (image: alpine) on it.

Here my ```.gitlab-ci.yml``` : 

```yaml
stages:
  - unit-test

variables:
  LC_ALL: 'en_US.UTF-8'
  LANG: 'en_US.UTF-8'
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - node -v
  - npm -v
  - yarn -v

detox-android:
  stage: unit-test
  image: reactnativecommunity/react-native-android
  before_script:
    - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - yarn install:module_only
  script:
    - mkdir -p /root/.android && touch /root/.android/repositories.cfg
    #- $ANDROID_HOME/tools/bin/sdkmanager --list --verbose
    - echo yes | $ANDROID_HOME/tools/bin/sdkmanager --channel=0 --verbose "system-images;android-25;google_apis;armeabi-v7a"
    - echo no | $ANDROID_HOME/tools/bin/avdmanager --verbose create avd --force --name "Pixel_API_28_AOSP" --package "system-images;android-25;google_apis;armeabi-v7a" --sdcard 200M --device 11
    - echo "Waiting emulator is ready..."
    - emulator -avd "Pixel_API_28_AOSP" -debug-init -no-window -no-audio -gpu swiftshader_indirect -show-kernel &
    - adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
    - echo "Emulator is ready!"
    - yarn detox-emu:build:android
    - yarn detox-emu:test:android
  tags:
    - detox-android
  only:
    - ci/unit-test
```

here the script in my ```package.json``` for the ci:

```json
 {
scripts: {
"detox-emu:test:android": "npx detox test -c android.emu.release.ci --headless -l verbose",
"detox-emu:build:android": "npx detox build -c android.emu.release.ci"
}
}
```

here my ```.detoxrc.json```

```json
{
  "testRunner": "jest",
  "runnerConfig": "e2e/config.json",
  "configurations": {
    "android.real": {
      "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
      "build": "cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
      "type": "android.attached",
      "device": {
        "adbName": "60ac9404"
      }
    },
    "android.emu.debug": {
      "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
      "build": "cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_API_28_AOSP"
      }
    },
    "android.emu.release": {
      "binaryPath": "android/app/build/outputs/apk/release/app-release.apk",
      "build": "cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release && cd ..",
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_API_28_AOSP"
      }
    },
    "android.emu.release.ci": {
      "binaryPath": "android/app/build/outputs/apk/release/app-release.apk",
      "build": "cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release && cd ..",
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_API_28_AOSP"
      }
    }
  }
}
```

Here the things I tried many way to setup an android emulator on an EC2 but it's look working only with an emulator ```armeabi-v7a``` due to the cpu virtualisation. It's look like the latest emulator available for ```armeabi-v7a``` is ```system-images;android-25;google_apis;armeabi-v7a```. It's look like I can only run an emulator with sdkversion 25 on EC2 instance then.

On my mobile app, I'm using mapbox for some features that require with detox minSdkversion 26. That I set on my build.gradle as well.

You can see full logs of my CI in attachement. 
[Log_CI.txt](https://github.com/wix/Detox/files/5562522/Log_CI.txt)

I get an error because detox don't find my emulator for the name ```Pixel_API_28_AOSP```. This error could be related to the minSdkVersion ? Or I miss something in my CI ?

**Environment (please complete the following information):**
 - Detox: 17.10.2
 - React Native: 0.63.2
 - Device: emulator ```system-images;android-25;google_apis;armeabi-v7a```
 - OS: android

Thanks in advance for your help !
