### ISSUE TITLE
CI configuration example for Github Actions

### ISSUE THREAD

**Issue by olexandr13** [wix/Detox#2617]
It would be great to see the CI configuration example for Github Actions.

**Comment by yungkittty** [comment]
@olexandr13 these are my github actions for both android and ios :

`e2e_android.yml`
```
name: E2E (Android)

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: E2E (Android)
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install Yarn Dependencies
        run: yarn install

      - name: Install Java JDK
        uses: joschi/setup-jdk@v1
        with:
          java-version: 'openjdk8'
          architecture: 'x64'
        env:
          # https://github.com/actions/toolkit/issues/641#issuecomment-728963957
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Run Unit Test(s)
        run: yarn test

      - name: Run Detox Build
        run: yarn e2e:build android.emu.release

      - name: Run Detox Test(s)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: pixel
          avd-name: Pixel_API_29_AOSP
          script: bash ${{ github.workspace }}/scripts/run-e2e-android-release.sh

```

`e2e_ios.yml`
```
name: E2E (iOS)

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: E2E (iOS)
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install Yarn Dependencies
        run: yarn install

      - name: Install Pod Dependencies
        run: cd ./ios && pod install && cd ..

      - name: Install Detox Dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Run Unit Test(s)
        run: yarn test

      - name: Run Detox Build
        run: yarn e2e:build ios.sim.release

      - name: Run Detox Test(s)
        run: bash ${{ github.workspace }}/scripts/run-e2e-ios-release.sh

```

`run-e2e-android-release.sh`
```
#!/bin/bash

yarn start &

METRO_BUNDLER_PID=$!

yarn e2e:test android.emu.release --headless

DETOX_EXIT_CODE=$?

kill $METRO_BUNDLER_PID

exit $DETOX_EXIT_CODE
```

`run-e2e-ios-release.sh`
```
#!/bin/bash

yarn start &

METRO_BUNDLER_PID=$!

yarn e2e:test ios.sim.release

DETOX_EXIT_CODE=$?

kill $METRO_BUNDLER_PID

exit $DETOX_EXIT_CODE
```

`package.json`
```
...
    "e2e:build": "detox build --configuration",
    "e2e:test": "detox test --configuration",
...
```

`.detoxrc.json`
```
{
  "testRunner": "jest",
  "runnerConfig": XXXX,
  "configurations": {
    "ios.sim.debug": {
      "type": "ios.simulator",
      "binaryPath": XXXX,
      "build": XXXX,
      "device": {
        "type": "iPhone 8",
        "OS": "iOS 14.4"
      }
    },
    "ios.sim.release": {
      "type": "ios.simulator",
      "binaryPath": XXXX,
      "build": XXXX,
      "device": {
        "type": "iPhone 8"
      }
    },
    "android.emu.debug": {
      "type": "android.emulator",
      "binaryPath": XXXX,
      "utilBinaryPaths": ["./cache/test-butler-app.apk"],
      "build": XXXX,
      "device": {
        "avdName": "Pixel_API_29_AOSP"
      }
    },
    "android.emu.release": {
      "type": "android.emulator",
      "binaryPath": XXXX,
      "utilBinaryPaths": ["./cache/test-butler-app.apk"],
      "build": XXXX,
      "device": {
        "avdName": "Pixel_API_29_AOSP"
      }
    }
  }
}

```

Also, make sure to use Test Butler (I don't know if it works without it), else remove `utilBinaryPaths` from `.detoxrc.json`.

[This](https://github.com/wix/Detox/issues/2193#issuecomment-776908132) might help you to setup Test Butler.
