### ISSUE TITLE
thrown: "Exceeded timeout of 120000 ms for a hook.

### ISSUE THREAD

**Issue by gunnartorfis** [wix/Detox#3218]
### Description
When running the tests locally on my machine, the test work as expected. However on CircleCI I receive the described errors.
It seems like the app is being installed and uninstalled in a loop, very strange. 

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction
I'm not 100% sure how to reproduce this since this is only happening on CircleCI and Travis too. 
I've tried to set the environment running on CircleCI to be as identical to my machine as possible. Both have the same Node, Xcode and Homebrew versions. The only difference is I'm running on M1 12.1 and CircleCI uses macOS 11.6.2 

#### Expected behavior
The tests should initiate and run on both environments. 

#### Environment

 - Detox: ^19.4.5
 - React Native: 0.67.2
 - Node: 14.19
 - Device: iPhone 12
 - Xcode: 12.5.1
 - iOS: Probably 12
 - macOS: 11.6.2
 - Test-runner (select one): `jest-circus`
 
#### If you are experiencing a timeout in your test

- [x] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much), I have read [synchronization debug documentation](https://github.com/wix/DetoxSync/blob/master/IdleStatusDocumentation.md) and am providing the relevant synchronization debug output below:

#### If you are seeing a Detox build problem (e.g. during `npm install`, not `detox build`)

- [ ] I am providing the `npm install` log below:

<details>
 <summary>Npm logs</summary>
 <code>
 (paste logs here)
 </code>
</details>

#### Device and verbose Detox logs

- [ ] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:

<details>
 <summary>Detox logs</summary>
 <code>

GitHub doesn't allow me to upload such a large file (maximum body exceeded, 65536 chars). Full logs can be found here: https://drive.google.com/file/d/1ZSdd-nIGv1dWgua2lsu4tqhLcZvfNos6/view?usp=sharing

 </code>
</details>

<details>
 <summary>Device logs</summary>
 <code>
I'm not sure how to get these from CircleCI. Can someone help me with that?
 </code>
</details>

**Comment by andreupifarre** [comment]
I am currently experiencing the same issue in Detox: ^19.4.5

**Comment by andreupifarre** [comment]
I am currently experiencing the same issue in Detox: ^19.4.5

**Comment by d4vidi** [comment]
Your tests seems to hang trying to run this command:
```
14:36:54.747 detox[12679] DEBUG: [EXEC_CMD, #56] applesimutils --byId 1B18C8F5-57C4-47EE-B349-EA33FEFA9FDD --bundle is.timatorg.debug --restartSB --setPermissions calendar=YES,notifications=YES,location=inuse,camera=YES,photos=YES 
```

Is it possible that [AppleSimUtils](https://github.com/wix/AppleSimulatorUtils) isn't properly installed on the agent you get on circle CI? _Note: it does not come preinstalled on their agents -- you have to set it up yourself by adding it to the beginning on the buildscript._

**Comment by gunnartorfis** [comment]
It looks like I'm already installing AppleSimUtils. Here is my CircleCI config:
```
version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    macos:
      xcode: '13.2.1'

    working_directory: ~/repo

    steps:
      - checkout

      - node/install:
          node-version: '14.19'
          install-yarn: true

      - run: brew update
      - run: brew reinstall cocoapods
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: sudo gem install cocoapods
      - run: gem install CFPropertyList

      # Set up environment
      - run: npm install -g react-native-cli
      - run: npm install -g detox-cli

      # # run unit tests
      # - run: yarn install
      # - run: yarn test

      # Install dependencies
      - run: cd ~/repo
      - run: echo $NOONA_MOBILE_ENV > .env
      - run: yarn
      - run: cd ios && pod install && cd ..

      # run E2E tests
      - run: RN_SRC_EXT=e2e.ts detox build --configuration ios.sim.debug
      - run: RN_SRC_EXT=e2e.ts detox test --configuration ios.sim.debug --cleanup  --loglevel trace

workflows:
  deploy-dev:
    jobs:
      - build:
          context:
            - noona-dev
          filters:
            branches:
              only:
                - dev
                - detox2

```
