### ISSUE TITLE
Detox - Android not working with Git action - CI

### ISSUE THREAD

**Issue by dhavallogistic** [wix/Detox#3379]
### What happened?

I work in React native project and with it I have connect Detox test case flow.
I have created all test scenario and it's working fine with local terminal.
I have requirement to connect with Git action - CI flow and while integrating with it I am facing issue of .

A. _ERROR   | x86_64 emulation currently requires hardware acceleration!_ while Step no. 6 (Start Android emulator)
B. _[...test case name...] assigned to undefined_  while Step no. 7 (Detox test

I have follow this step to complete Git action CI flow..

1. Node install
2. Set up Java and JDK environment
3. Download Emulator and image
4. Install all dependency
5. Build Detox
6. Start Android emulator
7. Detox Test

![1](https://user-images.githubusercontent.com/88703366/167146017-1d5a5143-000d-401e-979a-62836adead0e.png)

Here is my e2e.yml file
**I am using this -> `runs-on: ubuntu-latest`**

```

jobs:
  app_build:
    name: Detox building & testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      # 1
      - name: Node
        uses: actions/setup-node@v1

      # 2
      - name: Use specific Java version for sdkmanager to work
        uses: joschi/setup-jdk@v2
        with:
          java-version: "openjdk8"
          architecture: "x64"

      # 3
      - name: Download Android Emulator Image
        run: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-29;google_apis;x86"
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd --force --name Pixel_API_29_AOSP --device "Pixel_API_29_AOSP" -d pixel --package 'system-images;android-29;google_apis;x86'
          $ANDROID_HOME/emulator/emulator -list-avds

      # 4
      - name: Install dependencies
        run: npm install

      # 4.1
      - name: Install reac-native-vision-camera - v2.13.0
        run: npm install react-native-vision-camera@2.13.0

      # 5
      - name: Build for detox
        run: |
          npx detox build e2e -c android.release

      # 6
      - name: Android Emulator
        timeout-minutes: 5
        continue-on-error: true
        run: |
          echo "Starting emulator"
          nohup $ANDROID_HOME/emulator/emulator -avd Pixel_API_29_AOSP -no-audio -no-snapshot -no-window &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
          $ANDROID_HOME/platform-tools/adb devices
          echo "Emulator started"

      # 7
      - name: Android Detox Test
        run: npx detox test -c android.git.release

```

### What was the expected behaviour?

Unlike iOS it's not start detox test command.
It stuck at 2 steps Start android emulator and other Detox test.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Write demo test case into your local
Create node.js YML file on Git action and paste above yml file code into it.
And than save YML file and you will get result in Actions tab.

### In what environment did this happen?

Detox version: 19.5.7
React Native version: 0.64.2
Device model: Pixel_API_29_AOSP 
Android version: API 29
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

### Detox logs

<details><summary>Detox logs</summary>

```
Run echo "Starting emulator"
Starting emulator
* daemon not running; starting now at tcp:5037
* daemon started successfully
WARNING | unexpected system image feature string, emulator might not function correctly, please try updating the emulator.
ERROR   | x86_64 emulation currently requires hardware acceleration!
CPU acceleration status: KVM requires a CPU that supports vmx or svm
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.

```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>
