### ISSUE TITLE
Travis CI Issues

### ISSUE THREAD

**Issue by alexgv14** [wix/detox#382]
#### Description
Trying to get a simple test running in travis ci using detox 5.9.3 but always fails with the following error in travis. However, works fine locally:
```
 if [ "$TO_TEST" = "IOS" ]; then detox test --configuration ios.sim.release --cleanup; fi
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.sim.release  --cleanup   
detox-server info 22:55:59: server listening on localhost:55038...
detox info 1: Searching for device matching iPhone 7... 
detox info 5: Launching device ABBD7191-486B-462F-80B4-AE08C5820DA1... 
detox info 9: Uninstalling com.dadesystems.relay... 
detox info 9: com.dadesystems.relay uninstalled 
detox info 10: Installing /Users/travis/build/DadeSystems/DadeMobileReact/ios/build/Build/Products/Release-iphonesimulator/DadeMobileReact.app... 
detox info 10: /Users/travis/build/DadeSystems/DadeMobileReact/ios/build/Build/Products/Release-iphonesimulator/DadeMobileReact.app installed 
detox info 11: Terminating com.dadesystems.relay... 
detox info 11: com.dadesystems.relay terminated 
detox info 12: Launching com.dadesystems.relay... 
detox info 12: com.dadesystems.relay launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F $HOME/Library/Developer/CoreSimulator/Devices/ABBD7191-486B-462F-80B4-AE08C5820DA1/data/tmp/detox.last_launch_app_log.{out,err} 
  1) "before all" hook
  0 passing (2m)
  1 failing
  1) "before all" hook:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```     

#### .travis.yml file
```
matrix:
  include:
    - language: objective-c
      osx_image: xcode8.3
      env: TO_TEST=IOS
    - language: node_js
      node_js: 7
      env: TO_TEST=REACT
install:
  - if [ "$TO_TEST" = "IOS" ]; then brew update; fi
  - if [ "$TO_TEST" = "IOS" ]; then brew tap wix/brew; fi
  - if [ "$TO_TEST" = "IOS" ]; then brew install wix/brew/applesimutils; fi
  - if [ "$TO_TEST" = "IOS" ]; then curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash; fi
  - if [ "$TO_TEST" = "IOS" ]; then export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"; fi
  - if [ "$TO_TEST" = "IOS" ]; then nvm install stable; fi
  - if [ "$TO_TEST" = "IOS" ]; then nvm use stable; fi
  - if [ "$TO_TEST" = "IOS" ]; then npm install -g react-native-cli; fi
  - if [ "$TO_TEST" = "IOS" ]; then npm install -g detox-cli; fi
  - if [ "$TO_TEST" = "IOS" ]; then npm install; fi
  - if [ "$TO_TEST" = "REACT" ]; then npm install; fi
script:
  - if [ "$TO_TEST" = "IOS" ]; then detox build --configuration ios.sim.release >& /dev/null; fi
  - if [ "$TO_TEST" = "IOS" ]; then detox test --configuration ios.sim.release --cleanup; fi
  - if [ "$TO_TEST" = "REACT" ]; then npm run coverage; fi
```      

#### Spec file
```
describe('LoginScreen', () => {
  beforeEach(async () => {
    await device.launchApp({permissions: {camera: 'YES'}});
  });
  
  
  it('should be able to login', async () => {
    await expect(element(by.id('password'))).toBeVisible();
    await element(by.id('password')).tap()
    await element(by.id('password')).typeText('admin\n');
    await expect(element(by.id('menuLinkIcon'))).toExist();
  });

});
```

#### Detox, Node, Device, Xcode and macOS Versions
* Detox: 5.9.3
* Node: 9
* Device: iPhone 7
* Xcode: 8.3
* macOS: OS X 10.12

#### Device and verbose Detox logs
```
detox verb 8: /usr/bin/xcrun simctl uninstall ABBD7191-486B-462F-80B4-AE08C5820DA1 com.dadesystems.relay 
detox info 8: Uninstalling com.dadesystems.relay... 
detox info 8: com.dadesystems.relay uninstalled 
detox verb 9: /usr/bin/xcrun simctl install ABBD7191-486B-462F-80B4-AE08C5820DA1 /Users/travis/build/DadeSystems/DadeMobileReact/ios/build/Build/Products/Release-iphonesimulator/DadeMobileReact.app 
detox info 9: Installing /Users/travis/build/DadeSystems/DadeMobileReact/ios/build/Build/Products/Release-iphonesimulator/DadeMobileReact.app... 
detox info 9: /Users/travis/build/DadeSystems/DadeMobileReact/ios/build/Build/Products/Release-iphonesimulator/DadeMobileReact.app installed 
detox verb 10: /usr/bin/xcrun simctl terminate ABBD7191-486B-462F-80B4-AE08C5820DA1 com.dadesystems.relay 
detox info 10: Terminating com.dadesystems.relay... 
detox info 10: com.dadesystems.relay terminated 
detox verb 11: /bin/cat /dev/null >$HOME/Library/Developer/CoreSimulator/Devices/ABBD7191-486B-462F-80B4-AE08C5820DA1/data/tmp/detox.last_launch_app_log.out 2>$HOME/Library/Developer/CoreSimulator/Devices/ABBD7191-486B-462F-80B4-AE08C5820DA1/data/tmp/detox.last_launch_app_log.err && SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/travis/Library/Detox/ios/bff0d76d21089bd5ceb79d050a3ee95e0bbd8e76/Detox.framework/Detox" /usr/bin/xcrun simctl launch --stdout=/tmp/detox.last_launch_app_log.out --stderr=/tmp/detox.last_launch_app_log.err ABBD7191-486B-462F-80B4-AE08C5820DA1 com.dadesystems.relay --args -detoxServer ws://localhost:55567 -detoxSessionId 6bd835ee-bb50-9923-6543-acd998abf01c 
detox info 11: Launching com.dadesystems.relay... 
detox verb 11: stdout: com.dadesystems.relay: 10990
detox verb 11: stdout: 
detox info 11: com.dadesystems.relay launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F $HOME/Library/Developer/CoreSimulator/Devices/ABBD7191-486B-462F-80B4-AE08C5820DA1/data/tmp/detox.last_launch_app_log.{out,err} 
detox verb ws send: {"type":"isReady","params":{},"messageId":-1000}
detox verb ws onMessage: {"type":"ready","messageId":-1000,"params":{}}
detox verb ws  
  LoginScreen
detox verb 12: applesimutils --simulator ABBD7191-486B-462F-80B4-AE08C5820DA1 --bundle com.dadesystems.relay --setPermissions camera=YES 
detox info 12: Trying to set permissions... 
detox info 12: Permissions are set 
detox verb 13: /bin/cat /dev/null >$HOME/Library/Developer/CoreSimulator/Devices/ABBD7191-486B-462F-80B4-AE08C5820DA1/data/tmp/detox.last_launch_app_log.out 2>$HOME/Library/Developer/CoreSimulator/Devices/ABBD7191-486B-462F-80B4-AE08C5820DA1/data/tmp/detox.last_launch_app_log.err && SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/travis/Library/Detox/ios/bff0d76d21089bd5ceb79d050a3ee95e0bbd8e76/Detox.framework/Detox" /usr/bin/xcrun simctl launch --stdout=/tmp/detox.last_launch_app_log.out --stderr=/tmp/detox.last_launch_app_log.err ABBD7191-486B-462F-80B4-AE08C5820DA1 com.dadesystems.relay --args -detoxServer ws://localhost:55567 -detoxSessionId 6bd835ee-bb50-9923-6543-acd998abf01c 
detox info 13: Launching com.dadesystems.relay... 
detox verb 13: stdout: com.dadesystems.relay: 11008
detox verb 13: stdout: 
detox info 13: com.dadesystems.relay launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F $HOME/Library/Developer/CoreSimulator/Devices/ABBD7191-486B-462F-80B4-AE08C5820DA1/data/tmp/detox.last_launch_app_log.{out,err} 
detox verb ws send: {"type":"isReady","params":{},"messageId":-1000}
detox verb ws onMessage: {"type":"ready","messageId":-1000,"params":{}}
detox verb ws  
detox verb ws send: {"type":"invoke","params":{"target":{"type":"Invocation","value":{"target":{"type":"EarlGrey","value":"instance"},"method":"detox_selectElementWithMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"matcherForAccessibilityID:","args":[{"type":"NSString","value":"password"}]}}]}},"method":"performAction:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYActions"},"method":"actionForTypeText:","args":[{"type":"NSString","value":"admin\n"}]}}]},"messageId":1}
    1) should be able to login
detox verb ws send: {"type":"cleanup","params":{"stopRunner":true},"messageId":2}
detox verb ws onMessage: {"type":"cleanupDone","messageId":2,"params":{}}
detox verb ws  
detox verb 14: /usr/bin/xcrun simctl shutdown ABBD7191-486B-462F-80B4-AE08C5820DA1 
detox info 14: Shutting down ABBD7191-486B-462F-80B4-AE08C5820DA1... 
detox info 14: ABBD7191-486B-462F-80B4-AE08C5820DA1 shut down 
  0 passing (4m)
  1 failing
  1) LoginScreen
       should be able to login:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  ```
