### ISSUE TITLE
Tests do not run in gitlab CI/CD on Android

### ISSUE THREAD

**Issue by dea1d** [wix/Detox#4182]
### Description

Good afternoon.

My goal is to automate the build and run e2e tests in our gitlab, but I ran into difficulty when trying to run the tests on an active Android emulator installed on a remote macOs server.

```
FAIL
  ● Test suite failed to run
    response not received
      at Timeout._onTimeout (node_modules/telnet-client/lib/index.js:169:20)
```

Detox cannot access it. Although the emulator itself is in active adb devices.

This is what my script for running tests looks like.

```
detox:
  extends: .parent
  stage: E2E.detox
  before_script:
    - git submodule update --remote
    - adb start-server
  script:
    - cd $SDK_ROOT/tools
    - ./emulator -avd Pixel_6_API_32 > /dev/null 2>&1 &
    - sleep 20
    - adb devices
    - sleep 20
    - cd $CI_PROJECT_DIR
    - npx detox build --configuration android.emu.e2e.release
    - npx detox test --configuration android.emu.e2e.release --headless --loglevel trace
  timeout: 30 minutes
  allow_failure: true
```

Locally, the tests themselves run and work, although I noticed that locally, despite the --headless parameter, there is still a connection to the application and only after that the tests are executed.

In CI, the assembly is not installed and there is no application in the remote emulator, perhaps this is the problem?

I would be grateful for any advice.

### Your environment

Detox version: latest
React Native version: 0.70.13
Node version: 16.6.0
Device model: SDK 32
OS: Android
Test-runner (select one): jest

### Stacktrace/logs:

15:25:58.247 detox[38599] B device allocate
  args: ({"type":"android.emulator","device":{"avdName":"Pixel_6_API_32"},"headless":true})
15:25:58.247 detox[38599] i child-process:EXEC_CMD "/Users/developer/Library/Android/sdk/emulator/emulator" -list-avds --verbose
15:25:58.301 detox[38599] i child-process:EXEC_SUCCESS Pixel_6_API_32
15:25:58.302 detox[38599] i child-process:EXEC_CMD "/Users/developer/Library/Android/sdk/emulator/emulator" -version -no-window
15:25:58.716 detox[38599] i child-process:EXEC_SUCCESS Android emulator version 30.9.4.0 (build_id 7759208) (CL:N/A)
Copyright (C) 2006-2017 The Android Open Source Project and many others.
This program is a derivative of the QEMU CPU emulator (www.qemu.org).
  This software is licensed under the terms of the GNU General Public
  License version 2, as published by the Free Software Foundation, and
  may be copied, distributed, and modified under those terms.
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
15:25:58.716 detox[38599] i device Detected emulator binary version { major: 30, minor: 9, patch: 4, toString: [Function: toString] }
15:25:58.717 detox[38599] i device:ALLOCATE_DEVICE Trying to allocate a device based on "Pixel_6_API_32"
15:25:58.718 detox[38599] i child-process:EXEC_CMD "/Users/developer/Library/Android/sdk/platform-tools/adb"  devices
15:25:58.765 detox[38599] i child-process:EXEC_SUCCESS List of devices attached
emulator-5554	device
15:25:58.766 detox[38599] i device:TELNET_CONNECTING port: 5554, host: localhost
15:26:00.274 detox[38599] E device allocate
  error: Error: response not received
      at Timeout._onTimeout
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
15:26:00.276 detox[38599] E lifecycle set up environment
  error: Error: response not received
      at Timeout._onTimeout
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
