### ISSUE TITLE
Unable to run detox tests on Github actions runners.

### ISSUE THREAD

**Issue by NikolaSimsic** [wix/Detox#4712]
So, 

My setup uses following:

Detox: 20.34.0 (Started from 19.x but had to convert due to RN 0.75 support)
Jest: 29.7.0

**Android:**
runs-on: ubuntu-22.04
```
- name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99- 
          kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
- name: "Run tests"
        uses: reactivecircus/android-emulator-runner@v2.32.0
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          profile: pixel
          cores: 3
          ram-size: 4096M
          heap-size: 512M
          avd-name: NATIVE_pixel_34
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            adb shell "rm -fr /data/local/tmp/detox"
            adb shell "mkdir -p /data/local/tmp/detox"
            adb push "detox/apps/app-appstore-debug.apk" "/data/local/tmp/detox/Application.apk"
            adb push "detox/apps/app-appstore-debug-androidTest.apk" "/data/local/tmp/detox/Test.apk"
            adb shell pm install -r -g -t /data/local/tmp/detox/Application.apk 2>/dev/null
            adb shell pm install -r -g -t /data/local/tmp/detox/Test.apk 2>/dev/null
            yarn workspaces foreach ${{ needs.scope.outputs.scope }} run test:e2e:android
```

**Output of Run tests stage:**

```
10:11:41.177 detox[2946] i Could not detect emulator binary version ChildProcessError: Command failed: "/usr/local/lib/android/sdk/emulator/emulator" -version 
/usr/local/lib/android/sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory
 .....
 java.lang.NoSuchMethodException: No such accessible method: matcherForTestId() on class: com.wix.detox.espresso.DetoxMatcher
```

**iOS:**
```
runs-on: macos-13
- name: Update Xcode
   run: sudo xcode-select --switch /Applications/Xcode_14.2.app
 - name: "Clean detox framework cache"
    run: npx detox clean-framework-cache
  - name: "Build detox framework cache"
     run: npx detox build-framework-cache
  - name: Install Detox Dependencies
    run: |
        brew tap wix/brew 
        brew install applesimutils
- name: "Run tests"
        env:
          DETOX_LOGLEVEL: trace
        run: yarn workspaces foreach ${{ needs.scope.outputs.scope }} run test:e2e:ios
```

Output:
```
 error: Command failed: xcrun simctl status_bar "iPhone 14" override --time "2023-01-01T12:00:00Z" --batteryState charged -- 
  batteryLevel 100 --wifiBars 3
  An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
  Unable to lookup in current state: Shutdown
```

I have tried different combinations of Github runners and test emulators/simulators. On each version there is a known issue, so I switched back from macos-14,15 and iPhone16 to iPhone 14 and iOS 16.

Is there any idea of what I might use in order to get this setup working? 
 

### What was the expected behaviour?

Tests should be able to execute. 
Problems started to occur when I switched from macos-12 which is deprecated. 

### Was it tested on latest Detox?

- [x] I have tested this issue on the latest Detox release and it still reproduces.

### In what environment did this happen?

Detox version: 20.34.0
React Native version: 0.75
Has Fabric (React Native's new rendering system) enabled: no
Node version: 20.16.0
Test-runner (select one): jest
