### ISSUE TITLE
Timeout exceeded on Travis CI

### ISSUE THREAD

**Issue by mgillory** [wix/detox#579]
#### Description

When running detox on Travis CI, `detox test` keeps crashing due to timeout. Locally runs it as supposed to.

Below the setup:

**package.json**

```
"detox": {
    "specs": "test/e2e",
    "runner-config": "test/e2e/mocha.opts",
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/ClassApp.app",
        "build": "xcodebuild -project ios/remy.xcodeproj -scheme remy -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7"
      },
      "ios.sim.release": {
        "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/ClassApp.app",
        "build": "xcodebuild -project ios/remy.xcodeproj -scheme remy -configuration Release -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7"
      }
    }
  }
```
**mocha.opts**
`--recursive --timeout 120000 --bail`

**init.js** - test setup

```
require('babel-polyfill');
const detox = require('detox');
const config = require('../../package.json').detox;

before(async () => {
  try {
    await detox.init(config);
  } catch (e) {
    console.log('exception do init', e);
  }
});

after(async () => {
  await detox.cleanup();
});
```
**travis.yml**

```
language: node_js
node_js: 8.9.4

matrix:
  include:
    - language: objective-c
      osx_image: xcode9
      xcode_sdk: iphonesimulator11.0

addons:
  artifacts: true

env:
  global:
  - NODE_VERSION=stable

install:
  - sudo launchctl limit maxfiles 2048 unlimited
  - sudo ulimit -n 10000
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

  - brew install watchman
  - brew install yarn --without-node
  - brew tap wix/brew
  - brew install wix/brew/applesimutils
  - yarn global add react-native-cli
  - yarn global add detox-cli
  - yarn

script:
  - detox build --configuration ios.sim.release > /dev/null 2>&1
  - detox clean-framework-cache && detox build-framework-cache
  - detox test --configuration ios.sim.release -l verbose --cleanup
  
after_failure:
  - tail -F $HOME/Library/Developer/CoreSimulator/Devices/5BABCDC9-5EAF-4E60-96C0-F78309091348/data/tmp/detox.last_launch_app_log.err

```
#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.00
* Node: 8.9.4
* Device: Travis CI
* Xcode: 9
* macOS: Travis
* React Native: 0.47.2

#### Device and verbose Detox logs

**detox test --configuration ios.sim.release -l verbose --cleanup**
```
node_modules/.bin/mocha test/e2e --opts test/e2e/mocha.opts --configuration ios.sim.release --loglevel verbose --cleanup    


detox info 18:50:20: server listening on localhost:57298...

detox verb ws onOpen [object Object]

detox verb ws send: {"type":"login","params":{"sessionId":"0bf8ae3f-c0dd-c8b7-ff95-46dd214e577a","role":"tester"},"messageId":0}

detox verb ws onMessage: {"type":"loginSuccess","params":{"sessionId":"0bf8ae3f-c0dd-c8b7-ff95-46dd214e577a","role":"tester"},"messageId":0}

detox verb ws  

detox verb 1: applesimutils --list "iPhone 7" --maxResults=1 

detox info 1: Searching for device matching iPhone 7... 

detox verb 7: /usr/bin/xcrun simctl uninstall 5BABCDC9-5EAF-4E60-96C0-F78309091348 com.digniti.ClassApp 

detox info 7: Uninstalling com.digniti.ClassApp... 

detox info 7: com.digniti.ClassApp uninstalled 

detox verb 8: /usr/bin/xcrun simctl install 5BABCDC9-5EAF-4E60-96C0-F78309091348 /Users/travis/build/classapp/remy/ios/build/Build/Products/Release-iphonesimulator/ClassApp.app 

detox info 8: Installing /Users/travis/build/classapp/remy/ios/build/Build/Products/Release-iphonesimulator/ClassApp.app... 

detox info 8: /Users/travis/build/classapp/remy/ios/build/Build/Products/Release-iphonesimulator/ClassApp.app installed 

detox verb 9: /usr/bin/xcrun simctl terminate 5BABCDC9-5EAF-4E60-96C0-F78309091348 com.digniti.ClassApp 

detox info 9: Terminating com.digniti.ClassApp... 

detox info 9: com.digniti.ClassApp terminated 

detox verb 10: /bin/cat /dev/null >$HOME/Library/Developer/CoreSimulator/Devices/5BABCDC9-5EAF-4E60-96C0-F78309091348/data/tmp/detox.last_launch_app_log.out 2>$HOME/Library/Developer/CoreSimulator/Devices/5BABCDC9-5EAF-4E60-96C0-F78309091348/data/tmp/detox.last_launch_app_log.err && SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/travis/Library/Detox/ios/96cff4e280a5ab0f8477cfbc9695c4c593500fbf/Detox.framework/Detox" /usr/bin/xcrun simctl launch --stdout=/tmp/detox.last_launch_app_log.out --stderr=/tmp/detox.last_launch_app_log.err 5BABCDC9-5EAF-4E60-96C0-F78309091348 com.digniti.ClassApp --args -detoxServer ws://localhost:57298 -detoxSessionId 0bf8ae3f-c0dd-c8b7-ff95-46dd214e577a 

detox info 10: Launching com.digniti.ClassApp... 

detox verb 10: stdout: com.digniti.ClassApp: 10715

detox verb 10: stdout: 

detox info 10: com.digniti.ClassApp launched. The stdout and stderr logs were recreated, you can watch them with:

        tail -F $HOME/Library/Developer/CoreSimulator/Devices/5BABCDC9-5EAF-4E60-96C0-F78309091348/data/tmp/detox.last_launch_app_log.{out,err} 

detox verb ws send: {"type":"isReady","params":{},"messageId":-1000}

detox verb ws onMessage: {"type":"ready","messageId":-1000,"params":{}}

detox verb ws  

  Login

detox verb ws send: {"type":"reactNativeReload","params":{},"messageId":-1000}

detox verb ws onMessage: {"type":"ready","messageId":-1000,"params":{}}

detox verb ws send: {"type":"cleanup","params":{"stopRunner":true},"messageId":12}

detox verb ws onMessage: {"type":"cleanupDone","messageId":12,"params":{}}

detox verb ws  

detox verb 11: /usr/bin/xcrun simctl shutdown 5BABCDC9-5EAF-4E60-96C0-F78309091348 

detox info 11: Shutting down 5BABCDC9-5EAF-4E60-96C0-F78309091348... 

detox info 11: 5BABCDC9-5EAF-4E60-96C0-F78309091348 shut down 



  0 passing (3m)

  1 failing



  1) Login

       should not login with email (wrong password):

     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  







child_process.js:614

    throw err;

    ^



Error: Command failed: node_modules/.bin/mocha test/e2e --opts test/e2e/mocha.opts --configuration ios.sim.release --loglevel verbose --cleanup    

    at checkExecSyncError (child_process.js:574:11)

    at Object.execSync (child_process.js:611:13)

    at runMocha (/Users/travis/build/classapp/remy/node_modules/detox/local-cli/detox-test.js:72:6)

    at Object.<anonymous> (/Users/travis/build/classapp/remy/node_modules/detox/local-cli/detox-test.js:50:5)

    at Module._compile (module.js:662:30)

    at Object.Module._extensions..js (module.js:673:10)

    at Module.load (module.js:575:32)

    at tryModuleLoad (module.js:515:12)

    at Function.Module._load (module.js:507:3)

    at Function.Module.runMain (module.js:703:10)
```

**tail -F $HOME/Library/Developer/CoreSimulator/Devices/5BABCDC9-5EAF-4E60-96C0-F78309091348/data/tmp/detox.last_launch_app_log.err**

```
2018-02-22 18:51:51.715 ClassApp[10715:28805] Tapping on key: l.

2018-02-22 18:51:51.772 ClassApp[10715:28805] Attempting to type key ..

2018-02-22 18:51:51.773 ClassApp[10715:28805] Tapping on key: ..

2018-02-22 18:51:51.929 ClassApp[10715:28805] Attempting to type key c.

2018-02-22 18:51:51.930 ClassApp[10715:28805] Tapping on key: c.

2018-02-22 18:51:52.020 ClassApp[10715:28805] Attempting to type key o.

2018-02-22 18:51:52.020 ClassApp[10715:28805] Tapping on key: o.

2018-02-22 18:51:52.095 ClassApp[10715:28805] Attempting to type key m.

2018-02-22 18:51:52.098 ClassApp[10715:28805] Tapping on key: m.

2018-02-22 18:53:41.290 ClassApp[10715:29688] XPC connection interrupted
```
